version: "3.8"

services:
  app:
    image: golang:1.21.0
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: go run main.go
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=order

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "order_db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: